version: '3'

volumes:
  static:
  database:

services:
  hellodjango_blog_tutorial:
    build:
      context: .
      dockerfile: compose/production/django/Dockerfile
    image: tiny_blog
    container_name: tiny_blog
    working_dir: /app
    volumes:
      - database:/app/database
      - static:/app/static
    env_file:
      - .envs/.production
    ports:
      - "8000:8000"
    command: /start.sh

  nginx:
    build:
      context: .
      dockerfile: compose/production/nginx/Dockerfile
    image: tiny_blog_nginx
    container_name: tiny_blog_nginx
    volumes:
      - static:/apps/tiny_blog/static
    ports:
      - "80:80"
      - "443:443"